### ISSUE TITLE
Move lootr data into folder

### ISSUE THREAD

**Issue by itsdinkd** [Commoble/looot#3]
the data folder is spammed with lootr.dat files (over 2600 files from 3 weeks)
My suggestion would be creating a parent folder for this
/world/data/lootr

![image](https://user-images.githubusercontent.com/35115304/148496589-46cc67df-a283-4ef9-adf3-4053865db905.png)

**Comment by Commoble** [comment]
Hello! Lootr is a different and unrelated mod that is not made or maintained by me, you should report this to lootr and not looot

<https://www.curseforge.com/minecraft/mc-mods/lootr>
<https://github.com/noobanidus/lootr/issues>
