### ISSUE TITLE
Loot Modifiers not working with type looot:add_table?

### ISSUE THREAD

**Issue by SparkleArts** [Commoble/looot#4]
I make a Mod where an Item will be added to various Chest Loot Tables.

The first Structure I seek is the Monster Room/Simple Dungeon.

I'm using Looot 1.1.1.0 for 1.18.2.

[loot modifiers not working.zip](https://github.com/Commoble/looot/files/10784451/loot.modifiers.not.working.zip)

**Comment by Commoble** [comment]
For the record, it doesn't work because that add_table was added in 1.19.2. I'll add a history blurb to the github wiki so fewer people get confused about this
